-- BASIC LEVEL --
-- Display all columns from the members table. --
SELECT 
    *
FROM
    Members;
    
-- Display the names and cities of all members. --
SELECT 
    Member_Name, City
FROM
    Members;
    
-- Find all members who belong to the Thane branch. --
SELECT 
    B.Branch_ID, B.City, M.Member_Name
FROM
    Branches B
        JOIN
    Members M ON B.Branch_ID = M.Branch_ID
WHERE
    B.City = 'Thane';
    
-- Display all trainers whose specialization is Strength Training. --
SELECT 
    *
FROM
    Trainers
WHERE
    Specialization = 'Strength Training';
    
-- Show all plans along with their prices, sorted from highest price to lowest price. --
SELECT 
    *
FROM
    Plans
ORDER BY Price DESC;

-- Find all subscriptions that started in the year 2025. --
SELECT 
    *
FROM
    Subscriptions
WHERE
    YEAR(Start_Date) = '2025';
    
-- Display all payments made using UPI. --
SELECT 
    *
FROM
    Payments
WHERE
    Payment_Mode = 'UPI';
    
-- Find members whose age is between 25 and 35 years. --
SELECT 
    *
FROM
    Members
WHERE
    Age BETWEEN 25 AND 35;
    
-- Display the first 20 attendance records ordered by Attendance_Date. --
SELECT 
    *
FROM
    Attendance
ORDER BY Attendance_Date
LIMIT 20;

-- Count the total number of members in the gym. --
SELECT 
    COUNT(*) AS Member_Count
FROM
    Members;
    
-- INTERMEDIATE LEVEL --
-- Display each member's name along with the branch they belong to. --
SELECT 
    M.Member_Name, B.Branch_ID, B.Branch_Name
FROM
    Members M
        JOIN
    Branches B ON M.Branch_ID = B.Branch_ID;
    
-- Find the total number of members in each branch. --
SELECT 
    B.Branch_ID,
    B.Branch_Name,
    B.City,
    COUNT(M.Member_ID) AS Member_Count
FROM
    Branches B
        JOIN
    Members M ON B.Branch_ID = M.Branch_ID
GROUP BY B.Branch_ID , B.Branch_Name , B.City;

-- Display each subscription along with the corresponding plan name and price. --
SELECT 
    S.Subscription_ID, P.Plan_ID, P.Plan_Name, P.Price
FROM
    Subscriptions S
        JOIN
    Plans P ON S.Plan_ID = P.Plan_ID
ORDER BY S.Subscription_ID;

-- Find the total revenue generated by each payment method. --
SELECT 
    Payment_Mode, SUM(Amount) AS Total_Revenue
FROM
    Payments
GROUP BY Payment_Mode;

-- Display the number of trainers working in each branch. --
SELECT 
    Branch_ID, COUNT(Trainer_ID) AS Trainer_Count
FROM
    Trainers
GROUP BY Branch_ID;

-- Find the average age of members in every city. --
SELECT 
    City, ROUND(AVG(Age),2) AS Average_Age
FROM
    Members
GROUP BY City;

-- Display members who have purchased the Quarterly Premium plan. --
SELECT 
    S.Member_ID, M.Member_Name, P.Plan_ID, P.Plan_Name
FROM
    Subscriptions S
        JOIN
    Members M ON S.Member_ID = M.Member_ID
        JOIN
    Plans P ON S.Plan_ID = P.Plan_ID
WHERE
    P.Plan_ID = 'P1';
    
-- Find branches having more than 500 members. --
SELECT 
    Branch_ID, COUNT(Member_ID) AS Member_Count
FROM
    Members
GROUP BY Branch_ID
HAVING COUNT(Member_ID) > 500;

-- Calculate the total amount collected by each branch through subscriptions. --
SELECT 
    B.Branch_ID,
    B.Branch_Name,
    B.City,
    SUM(S.Amount_Paid) AS Total_Amount_Collected
FROM
    Branches B
        JOIN
    Members M ON B.Branch_ID = M.Branch_ID
        JOIN
    Subscriptions S ON M.Member_ID = S.Member_ID
GROUP BY B.Branch_ID , B.Branch_Name , B.City;

-- Find the earliest and latest subscription start date for every member. --
SELECT 
    M.Member_ID,
    M.Member_Name,
    MIN(S.Start_Date) AS Earliest,
    MAX(S.Start_Date) AS Latest
FROM
    Members M
        LEFT JOIN
    Subscriptions S ON M.Member_ID = S.Member_ID
GROUP BY M.Member_ID , M.Member_Name;

-- 	ADVANCED LEVEL --
-- Find the top 10 members who have spent the highest total amount on subscriptions. --
SELECT 
    M.Member_ID, M.Member_Name, SUM(P.Amount) AS Member_Spend
FROM
    Members M
        JOIN
    Payments P ON M.Member_ID = P.Member_ID
GROUP BY M.Member_ID , M.Member_Name
ORDER BY SUM(P.Amount) DESC
LIMIT 10;

-- Display members who have renewed their subscription more than 5 times. --
SELECT 
    M.Member_ID,
    M.Member_Name,
    COUNT(S.Subscription_ID) - 1 AS Total_Renewals
FROM
    Members M
        JOIN
    Subscriptions S ON M.Member_ID = S.Member_ID
GROUP BY M.Member_ID , M.Member_Name
HAVING COUNT(S.Subscription_ID) - 1 > 5;

-- Find the most popular subscription plan based on the number of subscriptions. --
SELECT 
    P.Plan_ID,
    P.Plan_Name,
    P.Price,
    P.Duration_Days,
    COUNT(S.Subscription_ID) AS Subscribed_Times
FROM
    Plans P
        JOIN
    Subscriptions S ON P.Plan_ID = S.Plan_ID
GROUP BY P.Plan_ID , P.Plan_Name , P.Price , P.Duration_Days
ORDER BY Subscribed_Times DESC
LIMIT 1;

-- Calculate the average attendance per member. --
SELECT 
    ROUND(AVG(Attendance_Count), 2) AS Average_Attendance_per_Member
FROM
    (SELECT 
        Member_ID, COUNT(*) AS Attendance_Count
    FROM
        Attendance
    GROUP BY Member_ID) AS Member_Attendance;

-- Find the member(s) with the highest number of attendance records. --
SELECT 
    M.Member_ID,
    M.Member_Name,
    COUNT(A.Attendance_ID) AS Attendance_Count
FROM
    Members M
        JOIN
    Attendance A ON M.Member_ID = A.Member_ID
GROUP BY M.Member_ID , M.Member_Name
ORDER BY Attendance_Count DESC
LIMIT 50;

-- Display members who have never renewed their subscription.--
SELECT 
    M.Member_ID, M.Member_Name
FROM
    Members M
        JOIN
    Subscriptions S ON M.Member_ID = S.Member_ID
GROUP BY M.Member_ID , M.Member_Name
HAVING COUNT(S.Subscription_ID) = 1;

-- Find the branch with the highest revenue generated from subscriptions. --
SELECT 
    B.Branch_ID,
    B.Branch_Name,
    B.City,
    SUM(S.Amount_Paid) AS Revenue
FROM
    Branches B
        JOIN
    Subscriptions S ON B.Branch_ID = S.Branch_ID
GROUP BY B.Branch_ID , B.Branch_Name , B.City
ORDER BY Revenue DESC
LIMIT 1;

-- Display the monthly revenue generated during 2025.--
SELECT 
    DATE_FORMAT(Start_Date, '%Y-%m') AS Year_Months,
    SUM(Amount_Paid) AS Monthly_Revenue
FROM
    Subscriptions
WHERE
    YEAR(Start_Date) = '2025'
GROUP BY Year_Months
ORDER BY Year_Months;

-- Find members who have purchased every available plan at least once. --
SELECT 
    M.Member_ID, M.Member_Name
FROM
    Members M
        JOIN
    Subscriptions S ON M.Member_ID = S.Member_ID
GROUP BY M.Member_ID , M.Member_ID
HAVING COUNT(DISTINCT S.Plan_ID) = (SELECT 
        COUNT(*)
    FROM
        Plans);
        
-- Find the trainer-to-member ratio for every branch. --
SELECT 
    B.Branch_ID,
    B.Branch_Name,
    COALESCE(M.Member_Count, 0) AS Total_Members,
    COALESCE(T.Trainer_Count, 0) AS Total_Trainers,
    ROUND(COALESCE(M.Member_Count, 0) / NULLIF(T.Trainer_Count, 0),
            2) AS Member_to_Ratio
FROM
    Branches B
        LEFT JOIN
    (SELECT 
        Branch_ID, COUNT(*) AS Member_Count
    FROM
        Members
    GROUP BY Branch_ID) M ON B.Branch_ID = M.Branch_ID
        LEFT JOIN
    (SELECT 
        Branch_ID, COUNT(*) AS Trainer_Count
    FROM
        Trainers
    GROUP BY Branch_ID) T ON B.Branch_ID = T.Branch_ID
ORDER BY B.Branch_ID;

-- EXPERT LEVEL --
-- Rank members within each branch based on their total spending using a window function. --
WITH Members_Spending AS (
SELECT 
    M.Member_ID,
    M.Member_Name,
    B.Branch_ID,
    B.Branch_Name,
    B.City,
    SUM(P.Amount) AS Total_Spend
FROM
    Members M
        JOIN
    Branches B ON M.Branch_ID = B.Branch_ID
        JOIN
    Payments P ON M.Member_ID = P.Member_ID
GROUP BY M.Member_ID , M.Member_Name , B.Branch_ID , B.Branch_Name , B.City
)

SELECT 
    Branch_ID, Branch_Name, Member_Name, Total_Spend,
	ROW_NUMBER() OVER(PARTITION BY Branch_ID ORDER BY Total_Spend DESC) AS Ranked
FROM
    Members_Spending;
    
-- For every member, display the current subscription along with the previous subscription. --
SELECT
    S.Member_ID,
    S.Subscription_ID,
    P.Plan_Name AS Current_Plan,
    S.Start_Date,
    S.End_Date,

    LAG(S.Subscription_ID)
        OVER (
            PARTITION BY S.Member_ID
            ORDER BY S.Start_Date
        ) AS Previous_Subscription_ID,

    LAG(P.Plan_Name)
        OVER (
            PARTITION BY S.Member_ID
            ORDER BY S.Start_Date
        ) AS Previous_Plan,

    LAG(S.Start_Date)
        OVER (
            PARTITION BY S.Member_ID
            ORDER BY S.Start_Date
        ) AS Previous_Start_Date,

    LAG(S.End_Date)
        OVER (
            PARTITION BY S.Member_ID
            ORDER BY S.Start_Date
        ) AS Previous_End_Date

FROM Subscriptions S
JOIN Plans P
ON S.Plan_ID = P.Plan_ID
ORDER BY
    S.Member_ID,
    S.Start_Date;
    
-- Calculate the revenue growth percentage for every month compared to the previous month. --
WITH Current_Revenue AS(
SELECT 
    DATE_FORMAT(Payment_Date, '%Y-%m') AS Months,
    SUM(Amount) AS Monthly_Revenue
FROM
    Payments
GROUP BY Months
ORDER BY Months),

Revenue_Comparison AS(
SELECT 
	Months, 
    Monthly_Revenue, 
    LAG(Monthly_Revenue) 
		OVER (ORDER BY Months) AS Previous_Month_Revenue
FROM 
	Current_Revenue
)

SELECT 
    Months,
    Monthly_Revenue,
    Previous_Month_Revenue,
    ROUND((Monthly_Revenue - Previous_Month_Revenue) * 100.0 / Previous_Month_Revenue,
            2) AS Revenue_Growth_Perc
FROM
    Revenue_Comparison; 
    
-- Find the top 3 revenue-generating branches using DENSE_RANK(). --
SELECT 
    B.Branch_ID,
    B.Branch_Name,
    B.City,
    SUM(S.Amount_Paid) AS Revenue,
    DENSE_RANK() OVER (ORDER BY SUM(S.Amount_Paid) DESC) AS Branches_Rank
FROM
    Branches B
        JOIN
    Subscriptions S ON B.Branch_ID = S.Branch_ID
GROUP BY B.Branch_ID , B.Branch_Name , B.City
LIMIT 3;

-- Find the top 5 members with the highest attendance in each branch using a window function. --
WITH Attendees AS (
SELECT 
    Branch_ID, Member_ID, COUNT(*) AS Attendance_Count
FROM
    Attendance
GROUP BY Branch_ID , Member_ID
)

SELECT 
    Branch_ID, Member_ID, Attendance_Count,
    ROW_NUMBER() OVER (PARTITION BY Branch_ID ORDER BY Attendance_Count DESC) AS Top_5
FROM
    Attendees
LIMIT 5;

-- Find members who renewed their subscription within 7 days after the previous subscription expired. --
WITH Previous_Subscription AS(
SELECT 
    M.Member_ID,
    M.Member_Name,
    S.Subscription_ID,
    S.Start_Date,
    S.End_Date,
    LAG(S.End_Date) OVER (PARTITION BY M.Member_ID ORDER BY End_Date) AS Previous_End_Date
FROM
    Members M
        JOIN
    Subscriptions S ON M.Member_ID = S.Member_ID
    )

SELECT 
    Member_ID,
    Member_Name,
    Start_Date,
    End_Date,
    Previous_End_Date,
    DATEDIFF(Start_Date, Previous_End_Date) AS Days_to_Renew
FROM
    Previous_Subscription
WHERE
    Previous_End_Date IS NOT NULL
        AND DATEDIFF(Start_Date, Previous_End_Date) BETWEEN 0 AND 7
ORDER BY Member_ID , Start_Date;

-- Display each member's lifetime value (LTV), total attendance count, total subscriptions, and average amount spent in a single query. --
SELECT 
    M.Member_ID,
    M.Member_Name,
    COALESCE(A.LifeTime_Value, 0) AS Lifetime_Value,
    COALESCE(B.Total_Attendance, 0) AS Total_Attendance,
    COALESCE(A.Total_Subscriptions, 0) AS Total_Subscriptions,
    COALESCE(A.Avg_Amount_Spent, 0) AS Average_Amount_Spent
FROM
    Members M
        LEFT JOIN
    (SELECT 
        S.Member_ID,
            COUNT(S.Subscription_ID) AS Total_Subscriptions,
            SUM(P.Amount) AS LifeTime_Value,
            AVG(P.Amount) AS Avg_Amount_Spent
    FROM
        Subscriptions S
    JOIN Payments P ON S.Subscription_ID = P.Subscription_ID
    GROUP BY S.Member_ID) A ON M.Member_ID = A.Member_ID
        LEFT JOIN
    (SELECT 
        Member_ID, COUNT(*) AS Total_Attendance
    FROM
        Attendance
    GROUP BY Member_ID) B ON M.Member_ID = B.Member_ID
ORDER BY M.Member_ID;

-- Using a CTE, calculate the cumulative revenue generated by each branch over time. --
WITH Month_Revenue AS (
SELECT 
    S.Branch_ID,
    DATE_FORMAT(P.Payment_Date, '%Y-%m') AS Revenue_Month,
    SUM(P.Amount) AS Monthly_Revenue
FROM
    Subscriptions S
        JOIN
    Payments P ON S.Subscription_ID = P.Subscription_ID
GROUP BY S.Branch_ID , DATE_FORMAT(P.Payment_Date, '%Y-%m')
)

SELECT 
	B.Branch_Name, 
    M.Revenue_Month, 
    M.Monthly_Revenue,
	SUM(M.Monthly_Revenue) 
		OVER(PARTITION BY M.Branch_ID ORDER BY M.Revenue_Month) AS Cumulative_Revenue
FROM 
	Month_Revenue M 
JOIN Branches B 
	ON M.Branch_ID = B.Branch_ID
ORDER BY B.Branch_ID, M.Revenue_Month;

-- For every branch, identify the member contributing the highest lifetime revenue. --
WITH LTV AS (
SELECT 
    B.Branch_ID, S.Member_ID, SUM(P.Amount) AS Lifetime_Value
FROM
    Payments P
        JOIN
    Subscriptions S ON P.Subscription_ID = S.Subscription_ID
        JOIN
    Branches B ON B.Branch_ID = S.Branch_ID
GROUP BY B.Branch_ID , S.Member_ID
),
Ranking AS (
SELECT 
	Branch_ID, Member_ID, Lifetime_Value,
	ROW_NUMBER() OVER (PARTITION BY Branch_ID ORDER BY Lifetime_Value DESC) AS Ranked
FROM 
	LTV
)
SELECT 
    R.Branch_ID,
    B.Branch_Name,
    R.Member_ID,
    M.Member_Name,
    R.Lifetime_Value
FROM
    Ranking R
        JOIN
    Branches B ON R.Branch_ID = B.Branch_ID
        JOIN
    Members M ON R.Member_ID = M.Member_ID
WHERE
    R.Ranked = 1;
    
-- Build a single SQL query that generates a Branch Performance Report containing the following columns:
-- Branch Name | Total Members | Total Trainers | Total Subscriptions | Total Revenue | Average Member Age | Most Popular Plan | Highest Spending Member | Revenue Rank among all Branches --
WITH
-- TOTAL MEMBERS PER BRANCH -- 
Member_Count AS (
SELECT 
    Branch_ID,
    COUNT(*) AS Total_Members,
    AVG(Age) AS Average_Member_Age
FROM
    Members
GROUP BY Branch_ID
),
-- TOTAL TRAINERS PER BRANCH --
Trainer_Count AS (
SELECT 
    Branch_ID, COUNT(*) AS Total_Trainers
FROM
    Trainers
GROUP BY Branch_ID
),
-- TOTAL SUBSCRIPTIONS AND TOTAL REVENUE --
Subscription_Summary AS (
SELECT 
    Branch_ID,
    COUNT(*) AS Total_Subscriptions,
    SUM(Amount_Paid) AS Total_Revenue
FROM
    Subscriptions
GROUP BY Branch_ID
),
-- MOST POPULAR PLAN --
Popular_Plan AS (
SELECT 
	S.Branch_ID, P.Plan_Name,
	ROW_NUMBER() 
		OVER (PARTITION BY S.Branch_ID ORDER BY COUNT(*) DESC) AS RN
FROM 
	Subscriptions S 
JOIN Plans P 
	ON S.Plan_ID = P.Plan_ID 
GROUP BY S.Branch_ID, P.Plan_Name
),
-- HIGHEST SPENDING CUSTOMER --
Highest_Spender AS (
SELECT 
	Branch_ID, Member_Name, Total_Spent,
    ROW_NUMBER() OVER (PARTITION BY Branch_ID ORDER BY Total_Spent DESC) AS RN
FROM
	(SELECT 
    M.Branch_ID,
    M.Member_Name,
    SUM(S.Amount_Paid) AS Total_Spent
FROM
    Members M
        JOIN
    Subscriptions S ON M.Member_ID = S.Member_ID
GROUP BY M.Branch_ID , M.Member_ID , M.Member_Name) X
)

SELECT 
    B.Branch_Name,
    MC.Total_Members,
    TC.Total_Trainers,
    SS.Total_Subscriptions,
    SS.Total_Revenue,
    ROUND(MC.Average_Member_Age, 2) AS Average_Member_Age,
    PP.Plan_Name AS Most_Popular_Plan,
    HS.Member_Name AS Highest_Spending_Member,
	DENSE_RANK() OVER(ORDER BY SS.Total_Revenue DESC) AS Revenue_Rank
FROM
    Branches B
        LEFT JOIN
    Member_Count MC ON B.Branch_ID = MC.Branch_ID
        LEFT JOIN
    Trainer_Count TC ON B.Branch_ID = TC.Branch_ID
        LEFT JOIN
    Subscription_Summary SS ON B.Branch_ID = SS.Branch_ID
        LEFT JOIN
    Popular_Plan PP ON B.Branch_ID = PP.Branch_ID
        LEFT JOIN
    Highest_Spender HS ON B.Branch_ID = HS.Branch_ID AND HS.RN = 1
ORDER BY Revenue_Rank;